import type { TriviaCategory, TriviaGrade, TriviaLevel } from './trivia';

type SeedQ = {
  question: string;
  options: string[];
  correct_index: number;
  category: TriviaCategory;
  grade: TriviaGrade;
  difficulty: TriviaLevel;
  source: string;
};

function q(
  question: string,
  options: string[],
  correct_index: number,
  category: TriviaCategory,
  grade: TriviaGrade,
  difficulty: TriviaLevel,
): SeedQ {
  return { question, options, correct_index, category, grade, difficulty, source: 'seed' };
}

// ─── HISTORY — 10 easy · 10 medium · 10 hard ──────────────────────────────────

const history: SeedQ[] = [
  // easy
  q('What is the capital city of Lebanon?',
    ['Beirut','Tripoli','Sidon','Jounieh'], 0, 'history', '1', 'easy'),
  q('What tree is shown on the Lebanese flag?',
    ['Palm','Cedar','Olive','Pine'], 1, 'history', '1', 'easy'),
  q('Which sea lies to the west of Lebanon?',
    ['Red Sea','Black Sea','Mediterranean Sea','Dead Sea'], 2, 'history', '2', 'easy'),
  q('Who built the famous temples at Baalbek?',
    ['Greeks','Romans','Persians','Ottomans'], 1, 'history', '3', 'easy'),
  q('Byblos, one of the world\'s oldest cities, is located in:',
    ['Syria','Jordan','Israel','Lebanon'], 3, 'history', '4', 'easy'),
  q('The Phoenicians are credited with giving the world:',
    ['Numbers','The wheel','The alphabet','Gunpowder'], 2, 'history', '4', 'easy'),
  q('Lebanese Independence Day is celebrated on:',
    ['November 22','July 4','March 21','May 6'], 0, 'history', '4', 'easy'),
  q('World War II ended in which year?',
    ['1939','1945','1950','1918'], 1, 'history', '6', 'easy'),
  q('Napoleon Bonaparte was the emperor of which country?',
    ['Italy','Spain','Britain','France'], 3, 'history', '5', 'easy'),
  q('The first modern Olympic Games were held in which city?',
    ['Paris','London','Athens','Rome'], 2, 'history', '5', 'easy'),

  // medium
  q('Lebanon declared independence from France in which year?',
    ['1958','1920','1967','1943'], 3, 'history', '3', 'medium'),
  q('The ancient Phoenicians lived in the area of modern-day:',
    ['Lebanon','Greece','Egypt','Turkey'], 0, 'history', '4', 'medium'),
  q('The Lebanese Civil War began in which year?',
    ['1943','1967','1982','1975'], 3, 'history', '5', 'medium'),
  q('Gibran Khalil Gibran is famous for writing:',
    ['The Prophet','The Alchemist','Les Misérables','The Stranger'], 0, 'history', '5', 'medium'),
  q('Which empire ruled Lebanon for roughly 400 years before WWI?',
    ['Roman','Ottoman','French','British'], 1, 'history', '5', 'medium'),
  q('The Roman god Jupiter is equivalent to the Greek god:',
    ['Ares','Poseidon','Zeus','Apollo'], 2, 'history', '5', 'medium'),
  q('The Great Wall of China was mainly completed during which dynasty?',
    ['Ming','Han','Tang','Qing'], 0, 'history', '6', 'medium'),
  q('The Renaissance began in which country?',
    ['France','England','Germany','Italy'], 3, 'history', '6', 'medium'),
  q('Who was the first President of the United States?',
    ['Abraham Lincoln','Thomas Jefferson','George Washington','Benjamin Franklin'], 2, 'history', '5', 'medium'),
  q('Which war was ended by the Treaty of Versailles in 1919?',
    ['World War II','The Crimean War','World War I','The Korean War'], 2, 'history', '6', 'medium'),

  // hard
  q('Which Phoenician city is said to have founded Carthage in North Africa?',
    ['Sidon','Byblos','Beirut','Tyre'], 3, 'history', '6', 'hard'),
  q('Who was the Egyptian pharaoh during the construction of the Great Pyramid of Giza?',
    ['Ramesses II','Cleopatra','Khufu','Tutankhamun'], 2, 'history', '6', 'hard'),
  q('The Magna Carta was signed in which year?',
    ['1066','1215','1348','1492'], 1, 'history', '6', 'hard'),
  q('Which Roman emperor adopted Christianity as the official religion of Rome?',
    ['Julius Caesar','Nero','Constantine I','Augustus'], 2, 'history', '6', 'hard'),
  q('The Ottoman Empire reached its greatest extent under which sultan?',
    ['Mehmed II','Suleiman the Magnificent','Selim I','Bayezid II'], 1, 'history', '6', 'hard'),
  q('In which year did the Berlin Wall fall?',
    ['1987','1991','1989','1985'], 2, 'history', '6', 'hard'),
  q('The Battle of Thermopylae in 480 BC was fought between the Greeks and:',
    ['Romans','Persians','Macedonians','Carthaginians'], 1, 'history', '6', 'hard'),
  q('Which Lebanese politician was assassinated in February 2005?',
    ['Bashir Gemayel','Rafik Hariri','René Moawad','Pierre Gemayel'], 1, 'history', '6', 'hard'),
  q('The Treaty of Lausanne (1923) defined the borders of which country?',
    ['Lebanon','Syria','Turkey','Iraq'], 2, 'history', '6', 'hard'),
  q('Hannibal Barca crossed the Alps with elephants to attack which empire?',
    ['Persian','Greek','Roman','Macedonian'], 2, 'history', '6', 'hard'),
];

// ─── SAGESSIAN LIFE SKILLS — 10 easy · 10 medium · 10 hard ────────────────────

const sls: SeedQ[] = [
  // easy
  q('What should you say when you accidentally bump into someone?',
    ['Nothing','Excuse me','Laugh','Run away'], 1, 'sls', '1', 'easy'),
  q('Which of these is a healthy breakfast choice?',
    ['Candy bar','Oatmeal with fruit','Soda and chips','Ice cream'], 1, 'sls', '1', 'easy'),
  q('How many hours of sleep do school-age children generally need each night?',
    ['4–5 hours','9–11 hours','6–7 hours','12–14 hours'], 1, 'sls', '2', 'easy'),
  q('Which of these helps reduce stress the most?',
    ['Scrolling social media','Exercise and deep breathing','Eating junk food','Avoiding friends'], 1, 'sls', '3', 'easy'),
  q('What is the first step when solving a conflict with a friend?',
    ['Ignore them','Walk away forever','Listen to their point of view','Tell everyone about it'], 2, 'sls', '3', 'easy'),
  q('What does "empathy" mean?',
    ['Feeling angry at others','Understanding and sharing someone else\'s feelings','Being shy','Ignoring people'], 1, 'sls', '4', 'easy'),
  q('Which habit helps you focus better while studying?',
    ['Keeping your phone nearby','Studying in a quiet, tidy space','Studying with the TV on','Waiting until midnight'], 1, 'sls', '4', 'easy'),
  q('Recycling paper and plastic is an example of:',
    ['Wasting resources','Environmental responsibility','Being lazy','Ignoring nature'], 1, 'sls', '2', 'easy'),
  q('Why is it important to keep promises?',
    ['It is not important','It builds trust with others','It makes you popular','It earns you money'], 1, 'sls', '3', 'easy'),
  q('What is a "growth mindset"?',
    ['Thinking you can never improve','Believing abilities can improve with effort','Only trusting talent','Giving up when things are hard'], 1, 'sls', '5', 'easy'),

  // medium
  q('Which of these is an example of good time management?',
    ['Leaving all homework for Sunday night','Making a daily schedule and following it','Skipping assignments','Asking someone else to do your work'], 1, 'sls', '4', 'medium'),
  q('Active listening means:',
    ['Waiting for your turn to talk','Giving full attention and responding thoughtfully','Nodding while thinking about something else','Interrupting with your own ideas'], 1, 'sls', '5', 'medium'),
  q('A person with high self-discipline would most likely:',
    ['Quit when tasks get difficult','Stick to a study plan even when distractions arise','Only work when they feel like it','Depend on others for motivation'], 1, 'sls', '5', 'medium'),
  q('Which of these is NOT a healthy coping strategy for anger?',
    ['Taking deep breaths','Going for a walk','Counting to ten','Shouting at the nearest person'], 3, 'sls', '5', 'medium'),
  q('What does it mean to be "proactive"?',
    ['Waiting for others to fix problems','Taking initiative before problems arise','Reacting only after things go wrong','Blaming others for issues'], 1, 'sls', '6', 'medium'),
  q('The Pomodoro Technique is a method for:',
    ['Physical exercise','Cooking efficiently','Focused work with short breaks','Speed reading'], 2, 'sls', '6', 'medium'),
  q('Financial literacy means:',
    ['Knowing how to read novels','Understanding how to manage money','Being good at math tests','Knowing world currencies'], 1, 'sls', '6', 'medium'),
  q('Which of these best describes "digital citizenship"?',
    ['Using as many devices as possible','Behaving responsibly and ethically online','Avoiding all technology','Sharing all personal information online'], 1, 'sls', '5', 'medium'),
  q('Why is volunteering in your community beneficial?',
    ['It only benefits you personally','It builds social skills and helps others','It is required by law','It has no real benefit'], 1, 'sls', '4', 'medium'),
  q('Setting a SMART goal means it should be:',
    ['Simple, Meaningful, Achievable, Relevant, Timed','Specific, Measurable, Achievable, Relevant, Time-bound','Successful, Motivated, Active, Real, Tested','Short, Major, Approved, Rewarded, Timed'], 1, 'sls', '6', 'medium'),

  // hard
  q('Which cognitive bias makes us favor information that confirms our existing beliefs?',
    ['Dunning-Kruger effect','Confirmation bias','Sunk cost fallacy','Availability heuristic'], 1, 'sls', '6', 'hard'),
  q('Maslow\'s Hierarchy of Needs places which need at the very top?',
    ['Safety','Love and belonging','Self-actualization','Esteem'], 2, 'sls', '6', 'hard'),
  q('Emotional intelligence (EQ) includes all of the following EXCEPT:',
    ['Self-awareness','Empathy','IQ score','Social skills'], 2, 'sls', '6', 'hard'),
  q('The "sunk cost fallacy" refers to:',
    ['Investing in a sinking ship','Continuing a bad decision because of past investment','Refusing to spend money','Always choosing the cheapest option'], 1, 'sls', '6', 'hard'),
  q('Which study technique is most supported by cognitive science research?',
    ['Re-reading notes many times','Highlighting text in different colors','Spaced repetition and retrieval practice','Studying everything the night before'], 2, 'sls', '6', 'hard'),
  q('In conflict resolution, "active listening" is paired with which technique to confirm understanding?',
    ['Debating','Paraphrasing / reflective listening','Giving advice immediately','Changing the subject'], 1, 'sls', '6', 'hard'),
  q('Which leadership style gives team members maximum autonomy to make decisions?',
    ['Authoritarian','Democratic','Laissez-faire','Transactional'], 2, 'sls', '6', 'hard'),
  q('The "10,000-hour rule" popularized by Malcolm Gladwell suggests:',
    ['You need 10,000 friends to succeed','Deliberate practice of ~10,000 hours produces expertise','You should sleep 10,000 minutes a week','Talent alone leads to success in 10,000 days'], 1, 'sls', '6', 'hard'),
  q('Which economic principle describes trading what you do best for what others do best?',
    ['Supply and demand','Comparative advantage','Opportunity cost','Diminishing returns'], 1, 'sls', '6', 'hard'),
  q('Which psychological concept explains why people work harder when they believe they can improve?',
    ['Fixed mindset','Self-fulfilling prophecy','Growth mindset','Learned helplessness'], 2, 'sls', '6', 'hard'),
];

// ─── MATH — 10 easy · 10 medium · 10 hard ────────────────────────────────────

const math: SeedQ[] = [
  // easy
  q('What is 7 + 8?',
    ['13','14','15','16'], 2, 'math', '1', 'easy'),
  q('What is 15 − 6?',
    ['7','8','9','10'], 2, 'math', '1', 'easy'),
  q('What is 4 × 3?',
    ['10','11','12','13'], 2, 'math', '2', 'easy'),
  q('What is 20 ÷ 4?',
    ['3','4','5','6'], 2, 'math', '2', 'easy'),
  q('What is half of 18?',
    ['7','8','9','10'], 2, 'math', '2', 'easy'),
  q('How many sides does a triangle have?',
    ['2','3','4','5'], 1, 'math', '1', 'easy'),
  q('What is the value of π (pi) to two decimal places?',
    ['3.12','3.14','3.16','3.18'], 1, 'math', '4', 'easy'),
  q('What is 100 − 37?',
    ['53','63','73','83'], 1, 'math', '3', 'easy'),
  q('What is 9 × 9?',
    ['72','81','90','99'], 1, 'math', '3', 'easy'),
  q('Which number is a prime number?',
    ['9','15','17','21'], 2, 'math', '4', 'easy'),

  // medium
  q('What is 12² (12 squared)?',
    ['124','136','144','148'], 2, 'math', '4', 'medium'),
  q('What is 15% of 200?',
    ['20','25','30','35'], 2, 'math', '5', 'medium'),
  q('Solve: 3x + 5 = 20. What is x?',
    ['3','4','5','6'], 2, 'math', '5', 'medium'),
  q('What is the area of a rectangle with length 8 and width 5?',
    ['26','36','40','45'], 2, 'math', '4', 'medium'),
  q('What is the square root of 144?',
    ['10','11','12','13'], 2, 'math', '5', 'medium'),
  q('If a train travels 60 km/h for 2.5 hours, how far does it travel?',
    ['120 km','130 km','140 km','150 km'], 3, 'math', '5', 'medium'),
  q('What is 2⁵ (2 to the power of 5)?',
    ['16','32','64','128'], 1, 'math', '5', 'medium'),
  q('What is the perimeter of a square with side length 7?',
    ['21','28','35','49'], 1, 'math', '4', 'medium'),
  q('Convert 3/4 to a percentage.',
    ['55%','65%','75%','85%'], 2, 'math', '5', 'medium'),
  q('What is the LCM of 4 and 6?',
    ['8','10','12','24'], 2, 'math', '4', 'medium'),

  // hard
  q('Solve: 2x² − 8 = 0. What are the values of x?',
    ['x = ±2','x = ±4','x = ±8','x = ±16'], 0, 'math', '6', 'hard'),
  q('What is the sum of interior angles of a hexagon?',
    ['540°','600°','720°','900°'], 2, 'math', '6', 'hard'),
  q('A car depreciates 20% per year. After 2 years, what percentage of the original value remains?',
    ['60%','62%','64%','66%'], 2, 'math', '6', 'hard'),
  q('What is log₁₀(1000)?',
    ['2','3','4','10'], 1, 'math', '6', 'hard'),
  q('The probability of rolling a 6 twice in a row with a fair die is:',
    ['1/12','1/36','1/18','1/6'], 1, 'math', '6', 'hard'),
  q('What is the slope of the line passing through (2, 3) and (6, 11)?',
    ['1','1.5','2','2.5'], 2, 'math', '6', 'hard'),
  q('Simplify: (3x²y)(4xy³)',
    ['7x³y⁴','12x³y⁴','12x²y³','7x²y⁴'], 1, 'math', '6', 'hard'),
  q('If f(x) = x² + 3x, what is f(4)?',
    ['24','26','28','32'], 2, 'math', '6', 'hard'),
  q('What is the greatest common divisor (GCD) of 48 and 180?',
    ['6','12','18','24'], 1, 'math', '6', 'hard'),
  q('A triangle has sides 5, 12, and 13. What type of triangle is it?',
    ['Equilateral','Isosceles','Right-angled','Obtuse'], 2, 'math', '6', 'hard'),
];

// ─── LANGUAGES — 10 easy · 10 medium · 10 hard ───────────────────────────────

const languages: SeedQ[] = [
  // easy
  q('What is the plural of "child"?',
    ['Childs','Childes','Children','Childrens'], 2, 'languages', '2', 'easy'),
  q('Which word is a noun?',
    ['Run','Happy','Tree','Quickly'], 2, 'languages', '2', 'easy'),
  q('Which word means the opposite of "hot"?',
    ['Warm','Cool','Cold','Chill'], 2, 'languages', '1', 'easy'),
  q('Which sentence uses correct punctuation?',
    ['Whats your name?','What\'s your name?','Whats your name.','What\'s your name'], 1, 'languages', '3', 'easy'),
  q('What does the French word "bonjour" mean in English?',
    ['Goodbye','Please','Hello / Good day','Thank you'], 2, 'languages', '3', 'easy'),
  q('Which letter is silent in the word "knight"?',
    ['n','g','k','t'], 2, 'languages', '3', 'easy'),
  q('What is the past tense of "go"?',
    ['Goed','Gone','Went','Goes'], 2, 'languages', '4', 'easy'),
  q('Which word is an adjective?',
    ['Sing','Slowly','Beautiful','Eat'], 2, 'languages', '3', 'easy'),
  q('How do you say "thank you" in Arabic?',
    ['Marhaba','Shukran','Inshallah','Yalla'], 1, 'languages', '2', 'easy'),
  q('Which of these is a conjunction?',
    ['Quickly','And','Blue','Jump'], 1, 'languages', '4', 'easy'),

  // medium
  q('What is a synonym for "happy"?',
    ['Sad','Joyful','Angry','Tired'], 1, 'languages', '4', 'medium'),
  q('Which sentence is in the passive voice?',
    ['The chef cooked the meal.','The meal was cooked by the chef.','She is cooking dinner.','He cooked well.'], 1, 'languages', '5', 'medium'),
  q('What is the correct spelling?',
    ['Accomodate','Acommodate','Accommodate','Acomodate'], 2, 'languages', '5', 'medium'),
  q('What does the prefix "mis-" mean?',
    ['Again','Not / wrongly','Before','After'], 1, 'languages', '5', 'medium'),
  q('Which of these is a metaphor?',
    ['She ran as fast as a cheetah.','Life is a rollercoaster.','The dog barked loudly.','He is very tall.'], 1, 'languages', '5', 'medium'),
  q('What does "e.g." stand for in English?',
    ['Every good example','For example','And so on','That is'], 1, 'languages', '6', 'medium'),
  q('Which verb form follows "to" in an infinitive phrase?',
    ['Past tense','Base form','Gerund (-ing)','Participle'], 1, 'languages', '5', 'medium'),
  q('The Arabic word "مكتبة" (maktaba) means:',
    ['School','Hospital','Library / bookstore','Office'], 2, 'languages', '5', 'medium'),
  q('What literary device repeats the same consonant sound at the start of words?',
    ['Assonance','Rhyme','Alliteration','Onomatopoeia'], 2, 'languages', '5', 'medium'),
  q('Which sentence uses the subjunctive mood?',
    ['I wish I were taller.','He is very tired.','She runs every day.','They will arrive soon.'], 0, 'languages', '6', 'medium'),

  // hard
  q('Which language has the most native speakers worldwide?',
    ['English','Spanish','Hindi','Mandarin Chinese'], 3, 'languages', '6', 'hard'),
  q('What is the term for a word that sounds like the thing it describes (e.g., "buzz")?',
    ['Alliteration','Metaphor','Onomatopoeia','Hyperbole'], 2, 'languages', '6', 'hard'),
  q('In English grammar, what is a "dangling modifier"?',
    ['A modifier with no clear subject to modify','An extra adjective','A verb used as a noun','A double negative'], 0, 'languages', '6', 'hard'),
  q('Which language family does Arabic belong to?',
    ['Indo-European','Semitic','Sino-Tibetan','Dravidian'], 1, 'languages', '6', 'hard'),
  q('What is the literary term for an indirect reference to a person, event, or other work?',
    ['Allusion','Illusion','Metaphor','Allegory'], 0, 'languages', '6', 'hard'),
  q('In French, which gender article is used before a feminine noun?',
    ['Le','La','Les','Un'], 1, 'languages', '6', 'hard'),
  q('What does the Latin root "bene" (as in "benefit") mean?',
    ['Bad','Well / good','Many','Fast'], 1, 'languages', '6', 'hard'),
  q('Which of these sentences contains a split infinitive?',
    ['He wants to run fast.','She decided to boldly go.','They chose to leave early.','We need to plan carefully.'], 1, 'languages', '6', 'hard'),
  q('The word "serendipity" originates from the old Arabic/Persian name for which island?',
    ['Cyprus','Malta','Sri Lanka (Serendip)','Sicily'], 2, 'languages', '6', 'hard'),
  q('In Arabic, the root ك-ت-ب (k-t-b) relates to which concept?',
    ['Speaking','Eating','Reading','Writing'], 3, 'languages', '6', 'hard'),
];

// ─── FOOTBALL — 10 easy · 10 medium · 10 hard ────────────────────────────────

const football: SeedQ[] = [
  // easy
  q('How many players are on a football team on the field?',
    ['9','10','11','12'], 2, 'football', '1', 'easy'),
  q('How long is a standard football match (regulation time)?',
    ['60 minutes','75 minutes','90 minutes','120 minutes'], 2, 'football', '1', 'easy'),
  q('What colour card does a referee show to send a player off?',
    ['Blue','Yellow','Red','Green'], 2, 'football', '1', 'easy'),
  q('What does a yellow card warn a player about?',
    ['A foul or misconduct','Time wasting only','Being offside','Missing a penalty'], 0, 'football', '2', 'easy'),
  q('Which country is considered the birthplace of modern football?',
    ['Brazil','Germany','Spain','England'], 3, 'football', '2', 'easy'),
  q('What is the name of the area directly in front of the goal?',
    ['Corner area','Centre circle','Penalty area','Halfway line'], 2, 'football', '3', 'easy'),
  q('In which year does the FIFA World Cup take place?',
    ['Every 2 years','Every 3 years','Every 4 years','Every 5 years'], 2, 'football', '3', 'easy'),
  q('What is a "hat-trick" in football?',
    ['Three yellow cards in a match','Three goals by one player in one match','Scoring from a corner kick','Winning 3 games in a row'], 1, 'football', '3', 'easy'),
  q('Which position stands in front of the goal to stop the ball?',
    ['Defender','Midfielder','Forward','Goalkeeper'], 3, 'football', '2', 'easy'),
  q('How many officials (referees) are on the field during a standard match?',
    ['1','2','3','4'], 0, 'football', '4', 'easy'),

  // medium
  q('What does VAR stand for in football?',
    ['Video Assistance Referee','Virtual Action Review','Video Assistant Referee','Visual Aid Review'], 2, 'football', '4', 'medium'),
  q('Which country has won the most FIFA World Cups?',
    ['Germany','Argentina','Italy','Brazil'], 3, 'football', '4', 'medium'),
  q('How many substitutions are allowed per team in a standard match (FIFA rules since 2022)?',
    ['3','4','5','6'], 2, 'football', '4', 'medium'),
  q('Who is the all-time top scorer in the UEFA Champions League?',
    ['Messi','Ronaldo','Raúl','Benzema'], 1, 'football', '5', 'medium'),
  q('Which player is known as "El Pibe de Oro" (The Golden Boy)?',
    ['Pelé','Ronaldo','Maradona','Messi'], 2, 'football', '5', 'medium'),
  q('In which year was the first FIFA World Cup held?',
    ['1926','1930','1934','1938'], 1, 'football', '5', 'medium'),
  q('Which club plays at the Santiago Bernabéu stadium?',
    ['FC Barcelona','Atletico Madrid','Real Madrid','Sevilla'], 2, 'football', '5', 'medium'),
  q('A player is offside if they are nearer to the opponent\'s goal line than both the ball and:',
    ['The centre line','The goalkeeper only','The second-last defender','The last defender'], 2, 'football', '5', 'medium'),
  q('Which African country first reached a World Cup semi-final (2022)?',
    ['Nigeria','Senegal','Morocco','Cameroon'], 2, 'football', '5', 'medium'),
  q('The "Golden Boot" award at the World Cup goes to:',
    ['The best goalkeeper','The tournament\'s top scorer','The player of the tournament','The best young player'], 1, 'football', '5', 'medium'),

  // hard
  q('Who scored the "Hand of God" goal and in which tournament?',
    ['Pelé, 1970 WC','Ronaldo, 2002 WC','Maradona, 1986 WC','Zidane, 1998 WC'], 2, 'football', '6', 'hard'),
  q('Which team won the 1998–99 treble (Premier League, FA Cup, Champions League)?',
    ['Arsenal','Chelsea','Manchester United','Liverpool'], 2, 'football', '6', 'hard'),
  q('How many World Cup titles has Brazil won in total?',
    ['3','4','5','6'], 2, 'football', '6', 'hard'),
  q('Which country won the first ever FIFA World Cup in 1930?',
    ['Argentina','Uruguay','Brazil','France'], 1, 'football', '6', 'hard'),
  q('Which club has won the most UEFA Champions League / European Cup titles?',
    ['AC Milan','Bayern Munich','Real Madrid','Barcelona'], 2, 'football', '6', 'hard'),
  q('Cristiano Ronaldo\'s first senior international goal for Portugal came against which country?',
    ['Spain','Kazakhstan','Germany','Greece'], 1, 'football', '6', 'hard'),
  q('The 2022 FIFA World Cup was the first held in which Middle Eastern country?',
    ['UAE','Bahrain','Saudi Arabia','Qatar'], 3, 'football', '6', 'hard'),
  q('Which player has won the most Ballon d\'Or awards?',
    ['Cristiano Ronaldo','Ronaldinho','Lionel Messi','Zinedine Zidane'], 2, 'football', '6', 'hard'),
  q('What was the record score in a FIFA World Cup match (Australia vs American Samoa, 2001 OFC qualifier)?',
    ['15–0','22–0','31–0','36–0'], 2, 'football', '6', 'hard'),
  q('Which player controversially moved from Barcelona to PSG in 2021 for a world-record fee area?',
    ['Kylian Mbappé','Erling Haaland','Neymar Jr','Antoine Griezmann'], 0, 'football', '6', 'hard'),
];

// ─── FORMULA 1 — 10 easy · 10 medium · 10 hard ───────────────────────────────

const formula1: SeedQ[] = [
  // easy
  q('What shape is an F1 circuit (generally)?',
    ['A straight line','A loop or complex track','A figure-8','A circle only'], 1, 'formula1', '1', 'easy'),
  q('How many wheels does an F1 car have?',
    ['2','4','6','8'], 1, 'formula1', '2', 'easy'),
  q('What flag signals the end of an F1 race?',
    ['Red flag','Yellow flag','Black flag','Chequered flag'], 3, 'formula1', '2', 'easy'),
  q('What does DRS stand for in F1?',
    ['Direct Racing Speed','Drag Reduction System','Driver Response System','Dynamic Race Speed'], 1, 'formula1', '3', 'easy'),
  q('Which country hosts the Monaco Grand Prix?',
    ['Italy','France','Monaco','Spain'], 2, 'formula1', '3', 'easy'),
  q('What is a "pit stop" in F1?',
    ['A race penalty','A pause when the car enters the pit lane for tyres/fuel','A crash barrier','A type of overtake'], 1, 'formula1', '3', 'easy'),
  q('What colour are F1 safety car lights?',
    ['Red','Blue','Green','Yellow / orange'], 3, 'formula1', '4', 'easy'),
  q('Which team uses the colour red and is based in Italy?',
    ['Mercedes','Red Bull','Ferrari','McLaren'], 2, 'formula1', '4', 'easy'),
  q('Which driver is known by the nickname "Mad Max"?',
    ['Lewis Hamilton','Sebastian Vettel','Max Verstappen','Charles Leclerc'], 2, 'formula1', '4', 'easy'),
  q('A red flag during a race means:',
    ['Caution, slow down','Race is paused or stopped','Pit lane is open','A driver is disqualified'], 1, 'formula1', '4', 'easy'),

  // medium
  q('Who holds the record for the most F1 World Championships?',
    ['Ayrton Senna','Michael Schumacher / Lewis Hamilton (7 each)','Sebastian Vettel','Alain Prost'], 1, 'formula1', '5', 'medium'),
  q('Which F1 circuit is the fastest in terms of average speed?',
    ['Monaco','Spa-Francorchamps','Monza','Silverstone'], 2, 'formula1', '5', 'medium'),
  q('What is a "podium" in F1?',
    ['The starting grid','The top-3 finishers\' ceremony','The pit lane entrance','The media room'], 1, 'formula1', '5', 'medium'),
  q('How many points does an F1 driver earn for winning a race?',
    ['10','15','20','25'], 3, 'formula1', '5', 'medium'),
  q('Which constructor won the most consecutive F1 constructors\' titles (2010–2013)?',
    ['McLaren','Ferrari','Mercedes','Red Bull'], 3, 'formula1', '5', 'medium'),
  q('What type of tyres are used in wet conditions in F1?',
    ['Slick tyres','Intermediate or full wet tyres','Soft compound tyres','Hard compound tyres'], 1, 'formula1', '5', 'medium'),
  q('The F1 season consists of approximately how many races?',
    ['8–10','12–15','20–24','30+'], 2, 'formula1', '6', 'medium'),
  q('Which country hosted the first ever F1 World Championship race in 1950?',
    ['Italy','Germany','France','Great Britain'], 3, 'formula1', '6', 'medium'),
  q('What does the abbreviation "DNF" mean in race results?',
    ['Did Not Finish','Did Not Fuel','Driver Not Fast','Did Not Follow'], 0, 'formula1', '6', 'medium'),
  q('Lewis Hamilton drove for which team when he won his first World Championship in 2008?',
    ['Mercedes','McLaren','Ferrari','Renault'], 1, 'formula1', '6', 'medium'),

  // hard
  q('Which driver won the F1 World Championship in 2021 at the controversial Abu Dhabi finale?',
    ['Lewis Hamilton','Valtteri Bottas','Max Verstappen','Carlos Sainz'], 2, 'formula1', '6', 'hard'),
  q('Which F1 driver died during the 1994 San Marino Grand Prix at Imola?',
    ['Gilles Villeneuve','Niki Lauda','Ayrton Senna','Roland Ratzenberger'], 2, 'formula1', '6', 'hard'),
  q('The "undercut" strategy in F1 refers to:',
    ['Overtaking on the inside','Pitting earlier than a rival to gain position via faster fresh tyres','A type of aerodynamic setup','Racing under the safety car'], 1, 'formula1', '6', 'hard'),
  q('Which team used a "double diffuser" in 2009 that caused controversy?',
    ['Ferrari','McLaren','Brawn GP','Red Bull'], 2, 'formula1', '6', 'hard'),
  q('How many constructors\' championships has Ferrari won in total (up to 2023)?',
    ['10','14','16','18'], 2, 'formula1', '6', 'hard'),
  q('The "tyre deg" concept in F1 refers to:',
    ['Tyre pressure changes during a race','How quickly a tyre loses performance / wears down','The tyre warming procedure','Changing compound mid-race'], 1, 'formula1', '6', 'hard'),
  q('Which driver holds the record for the most race wins in F1 history?',
    ['Michael Schumacher','Sebastian Vettel','Lewis Hamilton','Ayrton Senna'], 2, 'formula1', '6', 'hard'),
  q('In F1, "ERS" (Energy Recovery System) harvests energy from which two sources?',
    ['Braking and exhaust gases','Wind and solar','Braking and turbocharger (MGU-H/MGU-K)','Battery and fuel cell'], 2, 'formula1', '6', 'hard'),
  q('Which circuit is known as "The Cathedral of Speed" due to its high-speed banking?',
    ['Spa','Suzuka','Monza','Silverstone'], 2, 'formula1', '6', 'hard'),
  q('Michael Schumacher won 5 consecutive F1 titles with Ferrari from:',
    ['1994–1998','2000–2004','2002–2006','1998–2002'], 1, 'formula1', '6', 'hard'),
];

// ─── BASKETBALL — 10 easy · 10 medium · 10 hard ──────────────────────────────

const basketball: SeedQ[] = [
  // easy
  q('How many players are on the court per team in basketball?',
    ['4','5','6','7'], 1, 'basketball', '1', 'easy'),
  q('How many points is a three-point shot worth?',
    ['1','2','3','4'], 2, 'basketball', '1', 'easy'),
  q('What does it mean to "dribble" in basketball?',
    ['Shoot the ball','Bounce the ball while moving','Pass the ball','Block a shot'], 1, 'basketball', '2', 'easy'),
  q('How high is the basketball hoop from the floor (NBA standard)?',
    ['8 feet','9 feet','10 feet','11 feet'], 2, 'basketball', '2', 'easy'),
  q('What is a "free throw" in basketball?',
    ['An unguarded shot from the free-throw line after a foul','A pass that leads to a score','A slam dunk','A shot from half court'], 0, 'basketball', '3', 'easy'),
  q('Which country created the sport of basketball?',
    ['England','Canada (invented by a Canadian)','USA','France'], 1, 'basketball', '3', 'easy'),
  q('What is the NBA?',
    ['National Baseball Association','National Basketball Association','National Boxing Arena','North Basketball Alliance'], 1, 'basketball', '3', 'easy'),
  q('How many periods (quarters) are in an NBA game?',
    ['2','3','4','5'], 2, 'basketball', '3', 'easy'),
  q('A "slam dunk" is when a player:',
    ['Shoots from 3-point range','Jumps and puts the ball directly through the hoop','Blocks a shot','Steals the ball'], 1, 'basketball', '2', 'easy'),
  q('Who is often called the "GOAT" (Greatest of All Time) of basketball?',
    ['LeBron James','Kobe Bryant','Shaquille O\'Neal','Michael Jordan'], 3, 'basketball', '4', 'easy'),

  // medium
  q('How many minutes is a standard NBA game?',
    ['32 minutes','40 minutes','48 minutes','60 minutes'], 2, 'basketball', '4', 'medium'),
  q('Which NBA team has won the most championships?',
    ['Los Angeles Lakers','Golden State Warriors','Chicago Bulls','Boston Celtics'], 3, 'basketball', '4', 'medium'),
  q('What is a "double-double" in basketball stats?',
    ['Scoring twice in one second','Reaching double digits in two stat categories in one game','Winning back-to-back games','Two consecutive three-pointers'], 1, 'basketball', '5', 'medium'),
  q('Which player holds the NBA record for most career points (surpassed in 2023)?',
    ['Michael Jordan','Kobe Bryant','LeBron James','Kareem Abdul-Jabbar'], 2, 'basketball', '5', 'medium'),
  q('In basketball, what is "travelling"?',
    ['Moving the ball quickly down the court','Taking too many steps without dribbling','Passing the ball backwards','Running out of bounds'], 1, 'basketball', '5', 'medium'),
  q('What does "pick and roll" mean in basketball?',
    ['Selecting a new ball','A common play where one player screens then cuts to the basket','Rolling the ball to a teammate','A defensive formation'], 1, 'basketball', '5', 'medium'),
  q('How long does a team have to attempt a shot (NBA shot clock)?',
    ['14 seconds','20 seconds','24 seconds','30 seconds'], 2, 'basketball', '5', 'medium'),
  q('What position typically plays closest to the basket and focuses on rebounds?',
    ['Point guard','Shooting guard','Small forward','Center'], 3, 'basketball', '5', 'medium'),
  q('Michael Jordan won how many NBA championships with the Chicago Bulls?',
    ['4','5','6','7'], 2, 'basketball', '5', 'medium'),
  q('FIBA Basketball World Cup is held every how many years?',
    ['2','3','4','5'], 2, 'basketball', '6', 'medium'),

  // hard
  q('What is a "triple-double" in basketball?',
    ['Three consecutive three-pointers','Double digit stats in three categories in one game','Winning three championships','Scoring 30+ in three games'], 1, 'basketball', '6', 'hard'),
  q('Wilt Chamberlain famously scored how many points in a single NBA game in 1962?',
    ['72','81','100','110'], 2, 'basketball', '6', 'hard'),
  q('Which coach holds the record for most NBA championship wins as head coach?',
    ['Pat Riley','Gregg Popovich','Phil Jackson','Larry Brown'], 2, 'basketball', '6', 'hard'),
  q('The "Dream Team" won gold at the 1992 Olympics representing which country?',
    ['Canada','USA','Spain','Yugoslavia'], 1, 'basketball', '6', 'hard'),
  q('What defensive strategy assigns each defender to guard a specific area of the court?',
    ['Man-to-man defense','Zone defense','Press defense','Trap defense'], 1, 'basketball', '6', 'hard'),
  q('Kobe Bryant won how many NBA MVP (Most Valuable Player) awards?',
    ['1','2','3','4'], 0, 'basketball', '6', 'hard'),
  q('The "Hack-a-Shaq" strategy involved intentionally fouling a player because:',
    ['He was too fast','He was a poor free-throw shooter','He was the best scorer','He fouled opponents deliberately'], 1, 'basketball', '6', 'hard'),
  q('Which country won the FIBA Basketball World Cup in 2023?',
    ['USA','Serbia','Germany','France'], 2, 'basketball', '6', 'hard'),
  q('What is the diameter of a standard NBA basketball hoop (rim) in inches?',
    ['14 inches','16 inches','18 inches','20 inches'], 2, 'basketball', '6', 'hard'),
  q('LeBron James was drafted as the #1 overall pick in which year?',
    ['2001','2002','2003','2004'], 2, 'basketball', '6', 'hard'),
];

// ─── Export ───────────────────────────────────────────────────────────────────

export const TRIVIA_SEED: SeedQ[] = [
  ...history, ...sls, ...math, ...languages, ...football, ...formula1, ...basketball,
];
